In [1]:
import numpy as np
import pandas as pd
from pandas import Series

In [2]:
dframe_wine=pd.read_csv("winequality-red.csv",sep=';')

In [3]:
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25,67,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15,54,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17,60,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11,34,0.9978,3.51,0.56,9.4,5

In [10]:
dframe_wine.groupby(dframe_wine['quality']).head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.700,0.00,1.90,0.076,11,34,0.99780,3.51,0.56,9.4,5
1,7.8,0.880,0.00,2.60,0.098,25,67,0.99680,3.20,0.68,9.8,5
2,7.8,0.760,0.04,2.30,0.092,15,54,0.99700,3.26,0.65,9.8,5
3,11.2,0.280,0.56,1.90,0.075,17,60,0.99800,3.16,0.58,9.8,6
4,7.4,0.700,0.00,1.90,0.076,11,34,0.99780,3.51,0.56,9.4,5
5,7.4,0.660,0.00,1.80,0.075,13,40,0.99780,3.51,0.56,9.4,5
7,7.3,0.650,0.00,1.20,0.065,15,21,0.99460,3.39,0.47,10.0,7
8,7.8,0.580,0.02,2.00,0.073,9,18,0.99680,3.36,0.57,9.5,7
16,8.5,0.280,0.56,1.80,0.092,35,103,0.99690,3.30,0.75,10.5,7
18,7.4,0.590,0.08,4.40,0.086,6,29,0.99740,3.38,0.50,9.0,4
19,7.9,0.320,0.51,1.80,0.341,17,56,0.99690,3.04,1.08,9.2,6
20,8.9,0.220,0.48,1.80,0.077,29,60,0.99680,3.39,0.53,9.4,6
24,6.9,0.400,0.14,2.40,0.085,21,40,0.99680,3.43,0.63,9.7,6
29,7.8,0.645,0.00,2.00,0.082,8,16,0.99640,3.38,0.59,9.8,6
37,8.1,0.380,0.28,2.10,0.066,13,30,0.99680,3.23,0.73,9.7,7
38,5.7,1.130,0.09,1.50,0.172,7,19,0.99400,3.50,0.48,9.8,4
41,8.8,0.610,0.30,2.80,0.088,17,46,0.99760,3.26,0.51,9.3,4
45,4.6,0.520,0.15,2.10,0.054,8,65,0.99340,3.90,0.56,13.1,4
62,7.5,0.520,0.16,1.90,0.085,12,35,0.99680,3.38,0.62,9.5,7
73,8.3,0.675,0.26,2.10,0.084,11,43,0.99760,3.31,0.53,9.2,4
267,7.9,0.350,0.46,3.60,0.078,15,37,0.99730,3.35,0.86,12.8,8
278,10.3,0.320,0.45,6.40,0.073,5,13,0.99760,3.23,0.82,12.6,8
390,5.6,0.850,0.05,1.40,0.045,12,88,0.99240,3.56,0.82,12.9,8
440,12.6,0.310,0.72,2.20,0.072,6,29,0.99870,2.88,0.82,9.8,8
455,11.3,0.620,0.67,5.20,0.086,6,19,0.99880,3.22,0.69,13.4,8
459,11.6,0.580,0.66,2.20,0.074,10,47,1.00080,3.25,0.57,9.0,3
517,10.4,0.610,0.49,2.10,0.200,5,16,0.99940,3.16,0.63,8.4,3
690,7.4,1.185,0.00,4.25,0.097,5,14,0.99660,3.63,0.54,10.7,3
832,10.4,0.440,0.42,1.50,0.145,34,48,0.99832,3.38,0.86,9.9,3
899,8.3,1.020,0.02,3.40,0.084,6,11,0.99892,3.48,0.49,11.0,3

In [12]:
def ranker(df):
    df['alc_content_rank']=np.arange(len(df))+1
    return df

In [13]:
dframe_wine.sort('alcohol',ascending=False,inplace=True)

C:\Users\venkataprudhviraj\AppData\Local\Enthought\Canopy\User\lib\site-packages\ipykernel\__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':

In [14]:
dframe_wine=dframe_wine.groupby('quality').apply(ranker)

In [15]:
dframe_wine.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.36,0.65,7.5,0.096,22,71,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19,50,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,1
144,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,2
1270,5.0,0.38,0.01,1.6,0.048,26,60,0.99084,3.70,0.75,14.0,6,3

In [16]:
dframe_wine[dframe_wine['alc_content_rank']==1]

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality,alc_content_rank
652,15.9,0.36,0.65,7.5,0.096,22,71,0.99760,2.98,0.84,14.9,5,1
588,5.0,0.42,0.24,2.0,0.060,19,50,0.99170,3.72,0.74,14.0,8,1
142,5.2,0.34,0.00,1.8,0.050,27,63,0.99160,3.68,0.79,14.0,6,1
821,4.9,0.42,0.00,2.1,0.048,16,42,0.99154,3.71,0.74,14.0,7,1
45,4.6,0.52,0.15,2.1,0.054,8,65,0.99340,3.90,0.56,13.1,4,1
899,8.3,1.02,0.02,3.4,0.084,6,11,0.99892,3.48,0.49,11.0,3,1

In [18]:
num_of_qual=dframe_wine['quality'].value_counts()
num_of_qual

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64